# Generated by Django 5.2 on 2025-09-03 15:25

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False,default = uuid.uuid4, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
