# Generated by Django 5.2 on 2025-09-03 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='weather',
            name='icon',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='weather',
            name='temp_c',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
