# Generated by Django 5.2 on 2025-09-03 16:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_weather_created_at_weather_icon_weather_temp_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name="id",
        ),
        migrations.AddField(
            model_name='weather',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
