# Generated by Django 5.2 on 2025-09-03 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_weather_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='date',
            field=models.CharField(default=datetime.date(2025, 9, 3), max_length=255),
        ),
    ]
