# Generated by Django 5.2 on 2025-09-03 20:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_weather_date'),
    ]

    operations = [
    ]
