# Generated by Django 5.2 on 2025-09-03 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_weather_temp_id_alter_weather_id'),
    ]

    operations = [
    ]
