# Generated by Django 5.2 on 2025-09-04 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_weather_date'),
    ]

    operations = [

        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.CharField(default=datetime.date(2025, 9, 4), max_length=255),
        ),
    ]
