# Generated by Django 5.2 on 2025-09-04 07:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_weather_temp_id_alter_weather_date'),
    ]

    operations = [

    ]
