# Generated by Django 5.2 on 2025-09-04 07:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_weather_temp_id'),
    ]

    operations = [

    ]
