# Generated by Django 5.2 on 2025-09-04 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_weather_temp_id_alter_weather_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, unique=True),
        ),
    ]
